### PR TITLE
Add workflow to build Docker image on tags

### PR DESCRIPTION
**Pull request by fpotier**
## Description

Push a new Docker image when a tag is created

### CODE REVIEW

**Review by bpedersen2 — COMMENTED** [review]
LGTM

**Review by bpedersen2 — APPROVED** [review]

**Comment by fpotier** [comment]
@bpedersen2 I think it would be a good idea to release a new version with the all the package upgrades and I also think that a relatively recent patch made the container configurable at runtime

**Comment by bpedersen2** [comment]
Yes, definetly.

But build fails ;)

```
/usr/bin/docker buildx build --iidfile /home/runner/work/_temp/docker-actions-toolkit-wuehXQ/build-iidfile-00b18d9961.txt --platform linux/amd64,linux/arm64/v8 --tag ghcr.io/scicatproject/landingpageserver:v3.2-rc1 --tag ghcr.io/scicatproject/landingpageserver:stable --metadata-file /home/runner/work/_temp/docker-actions-toolkit-wuehXQ/build-metadata-7694e5a423.json --push .
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```

**Comment by fpotier** [comment]
Ah I copied [this workflow](https://github.com/SciCatProject/scicat-backend-next/actions/workflows/build-release.yml) but it looks like it never actually ran.

**Pull request merged**
