### PR TITLE
Modernize landingpage

### PR DESCRIPTION
**Pull request by bpedersen2**
Modernize the landing page service:
 - use angular 17
 - use node 20
 - use same lint setup as on scicat frontend

## Tests included/Docs Updated?

- [ ]  Included for each change/fix?
- [X] Passing? (Merge will not be approved unless this is checked) 
- [x]  Docs updated?
- [X] New packages used/requires npm install?

### CODE REVIEW

**Comment by bpedersen2** [comment]
Fixes https://github.com/SciCatProject/LandingPageServer/security/dependabot/59

**Comment by bpedersen2** [comment]
Should update README to reflect the new versions used

**Comment by minottic** [comment]
I tried in another project to upgrade to angular 17 from 15 and the materials update was a mess. Does this work fine? is the rendering/style still ok?

**Comment by bpedersen2** [comment]
screenshot-landingpage k8s-test frm2 tum de-2024 03 28-11_30_40

Looks OK to me in our test instance

**Comment by bpedersen2** [comment]
[
screenshot-landingpage k8s-test frm2 tum de-2024 03 28-11_32_49
](url)

**Review by minottic — APPROVED** [review]

**Pull request merged**
